import mongoose from "mongoose";
import crypto from "crypto";

const tenantSchema = new mongoose.Schema({

  // ================= IDENTITY =================
  name: {
    type: String,
    required: true,
    trim: true
  },

  email: {
    type: String,
    required: true,
    unique: true,
    lowercase: true,
    trim: true
  },

  // ================= AUTH =================
  apiKey: {
    type: String,
    required: true,
    unique: true,
    index: true
  },

  // ================= WHATSAPP CREDENTIALS =================
  // These are all provided/returned by Meta — NOT entered manually by the client.
  //
  // Onboarding flow:
  //   1. Client enters their phone number in your frontend
  //   2. Meta Embedded Signup verifies & connects the number
  //   3. Meta returns phoneNumberId, wabaId, accessToken automatically
  //   4. Your backend stores them here
  //
  // phone      → provided by client (their real number e.g. +2203030255)
  // phoneNumberId → generated by Meta (identifies the number in the API)
  // wabaId     → generated by Meta (WhatsApp Business Account ID)
  // accessToken → generated by Meta (used to send messages)
  whatsapp: {
    phone: {
      type: String,
      trim: true,
      default: null
    },

    phoneNumberId: {
      type: String,
      unique: true,
      sparse: true,    // allows null/undefined during PENDING onboarding
      trim: true,
      default: null
    },

    wabaId: {
      type: String,
      trim: true,
      default: null
    },

    accessToken: {
      type: String,
      trim: true,
      default: null
    },

    verifyToken: {
      type: String,
      trim: true,
      default: null
    },

    apiVersion: {
      type: String,
      default: "v21.0",
      trim: true
    },

    // Track whether the WhatsApp number has been connected via Meta
    connected: {
      type: Boolean,
      default: false
    },

    // When the accessToken was last refreshed (long-lived tokens expire)
    tokenUpdatedAt: {
      type: Date,
      default: null
    }
  },

  // ================= PLAN =================
  plan: {
    type: String,
    enum: ["FREE", "STARTER", "PRO", "ENTERPRISE"],
    default: "FREE"
  },

  limits: {
    messagesPerMonth: { type: Number, default: 500 },
    maxMenuItems: { type: Number, default: 10 },
    maxAdmins: { type: Number, default: 1 }
  },

  usage: {
    messagesThisMonth: { type: Number, default: 0 },
    resetDate: { type: Date, default: () => new Date() }
  },

  // ================= STATUS =================
  // PENDING = registered but WhatsApp not yet connected
  // ACTIVE  = fully connected and operational
  // SUSPENDED = access blocked (e.g. non-payment)
  status: {
    type: String,
    enum: ["ACTIVE", "SUSPENDED", "PENDING"],
    default: "PENDING"     // starts PENDING until WhatsApp is connected
  },

  // ================= ADMIN CONTACT =================
  // Phone number for receiving platform alerts (e.g. token expiry) via WhatsApp.
  // This is the TENANT OWNER's number — separate from BusinessConfig.adminPhone
  // which is the per-business contact for order/booking alerts.
  adminPhone: {
    type: String,
    default: null,
    trim: true
  },

  // ================= META =================
  notes: { type: String, default: "" }

}, { timestamps: true });

// Auto-generate apiKey before saving
tenantSchema.pre("validate", function (next) {
  if (!this.apiKey) {
    this.apiKey = crypto.randomBytes(32).toString("hex");
  }
  next();
});

tenantSchema.set("toJSON", {
  transform: (doc, ret) => {
    // Never expose accessToken in API responses
    if (ret.whatsapp) delete ret.whatsapp.accessToken;
    delete ret.__v;
    return ret;
  }
});

export default mongoose.model("Tenant", tenantSchema);
