import mongoose from "mongoose";
import crypto from "crypto";

const tenantSchema = new mongoose.Schema({

  // ================= IDENTITY =================
  name: {
    type: String,
    required: true,
    trim: true
  },

  email: {
    type: String,
    required: true,
    unique: true,
    lowercase: true,
    trim: true
  },

  // ================= AUTH =================
  apiKey: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  // [FIX-6] Hashed version of apiKey for safe DB lookups.
  // authMiddleware looks up tenants by apiKeyHash (SHA-256 of the raw key)
  // so the plaintext key is never stored in or queried from MongoDB.
  // Run `node scripts/migrate-apikey-hash.js` to populate this for existing tenants,
  // then set APIKEY_MIGRATION_DONE=true in your env to disable the plaintext fallback.
  apiKeyHash: {
    type: String,
    index: true,
    sparse: true,  // allows null/missing (pre-migration tenants)
  },

  // ================= WHATSAPP CREDENTIALS =================
  // These are all provided/returned by Meta — NOT entered manually by the client.
  //
  // Onboarding flow:
  //   1. Client enters their phone number in your frontend
  //   2. Meta Embedded Signup verifies & connects the number
  //   3. Meta returns phoneNumberId, wabaId, accessToken automatically
  //   4. Your backend stores them here
  //
  // phone      → provided by client (their real number e.g. +2203030255)
  // phoneNumberId → generated by Meta (identifies the number in the API)
  // wabaId     → generated by Meta (WhatsApp Business Account ID)
  // accessToken → generated by Meta (used to send messages)
  whatsapp: {
    phone: {
      type: String,
      trim: true,
      default: null
    },

    phoneNumberId: {
      type: String,
      unique: true,
      sparse: true,    // skips indexing when field is absent (undefined) — NEVER set default: null here
      trim: true,
      // NO default: null — Mongoose would write null explicitly, MongoDB would then index it
      // and treat all PENDING tenants (without a phoneNumberId yet) as duplicates of each other.
      // Leaving this undefined means the sparse index only kicks in once a real value is stored.
    },

    wabaId: {
      type: String,
      trim: true,
      default: null
    },

    accessToken: {
      type: String,
      trim: true,
      default: null
    },

    verifyToken: {
      type: String,
      trim: true,
      default: null
    },

    apiVersion: {
      type: String,
      default: "v21.0",
      trim: true
    },

    // Track whether the WhatsApp number has been connected via Meta
    connected: {
      type: Boolean,
      default: false
    },

    // When the accessToken was last refreshed (long-lived tokens expire)
    tokenUpdatedAt: {
      type: Date,
      default: null
    }
  },

  // ================= PLAN =================
  plan: {
    type: String,
    enum: ["FREE", "STARTER", "PRO", "ENTERPRISE"],
    default: "FREE"
  },

  limits: {
    messagesPerMonth: { type: Number, default: 500 },
    maxMenuItems: { type: Number, default: 10 },
    maxAdmins: { type: Number, default: 1 }
  },

  usage: {
    messagesThisMonth: { type: Number, default: 0 },
    resetDate: { type: Date, default: () => new Date() }
  },

  // ================= STATUS =================
  // PENDING = registered but WhatsApp not yet connected
  // ACTIVE  = fully connected and operational
  // SUSPENDED = access blocked (e.g. non-payment)
  status: {
    type: String,
    enum: ["ACTIVE", "SUSPENDED", "PENDING"],
    default: "PENDING"     // starts PENDING until WhatsApp is connected
  },

  // ================= ONBOARDING STEP =================
  // 0 = not started (legacy email-only registration)
  // 1 = WhatsApp connected (tenant created via PUT /register/whatsapp)
  // 2 = basic business setup complete (name, businessMode, adminPhone)
  // 3 = advanced setup complete (menu, hours, payment, faq, settings)
  onboardingStep: {
    type:    Number,
    default: 0,
    min:     0,
    max:     3,
  },

  // ================= ADMIN CONTACT =================
  // Phone number for receiving platform alerts (e.g. token expiry) via WhatsApp.
  // This is the TENANT OWNER's number — separate from BusinessConfig.adminPhone
  // which is the per-business contact for order/booking alerts.
  adminPhone: {
    type:    String,
    default: null,
    trim:    true,
  },

  // ================= META =================
  notes: { type: String, default: "" }

}, { timestamps: true });

// Auto-generate apiKey before saving, and always keep apiKeyHash in sync.
tenantSchema.pre("validate", function (next) {
  if (!this.apiKey) {
    this.apiKey = crypto.randomBytes(32).toString("hex");
  }
  // Keep apiKeyHash in sync whenever apiKey is set/changed.
  // This means new tenants always get a hash without needing to run the migration.
  if (!this.apiKeyHash || this.isModified("apiKey")) {
    this.apiKeyHash = crypto.createHash("sha256").update(this.apiKey).digest("hex");
  }
  next();
});

tenantSchema.set("toJSON", {
  transform: (doc, ret) => {
    // Never expose credentials in API responses.
    // apiKey is returned explicitly ONLY by createTenant (reads the field directly).
    // All other serialisation paths (list, get, update) must never expose it.
    if (ret.whatsapp) delete ret.whatsapp.accessToken;
    delete ret.apiKey;
    delete ret.__v;
    return ret;
  }
});

export default mongoose.model("Tenant", tenantSchema);
